spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_book
    password: 123456
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    charset: utf-8
  http:
    encoding:
      charset: UTF-8
      force: true
